import { Category, Phrase } from './types';
import categories from './categories.json';
import gyaru from './phrases.gyaru.json';
import kansai from './phrases.kansai.json';
import edo from './phrases.edo.json';
import net from './phrases.net.json';
import otaku from './phrases.otaku.json';
import reiwa from './phrases.reiwa.json';
import heian from './phrases.heian.json';
import okinawa from './phrases.okinawa.json';

export function loadCategories(): Category[] {
  return categories as Category[];
}

export function findCategory(id: string): Category | undefined {
  return loadCategories().find((c) => c.id === id);
}

export function validatePhrase(p: Phrase): Phrase {
  const required: (keyof Phrase)[] = [
    'id',
    'categoryId',
    'term',
    'meaningEn',
    'meaningJa',
    'exampleJa',
    'exampleEn',
  ];
  for (const k of required) {
    if (!p[k]) throw new Error(`phrase ${p.id ?? '?'} missing ${k}`);
  }
  if (!p.tag || !['wakeru', 'itai', 'tsuujiru'].includes(p.tag.gachi)) {
    throw new Error(`phrase ${p.id} has invalid tag.gachi`);
  }
  return p;
}

// Code-switched English examples (the word dropped into English), keyed by term.
const MIX: Record<string, string> = {
  'あげぽよ': "Tonight's concert? I'm so agepoyo!",
  'MK5': "Late again?! I'm totally MK5 right now.",
  'チョベリバ': 'Got my test back… choberiba.',
  'パリピ': 'Out with the paripi till dawn.',
  'エモい': 'This song is so emoi at dusk.',
  '卍': 'Getting hyped — manji!',
  'おおきに': 'Thanks a million — ookini!',
  'なんでやねん': 'You forgot your wallet? Nandeyanen!',
  'ほんま': 'This is honma delicious.',
  'あかん': "Hey, you can't sleep here — akan de!",
  'めっちゃ': "It's meccha hot today.",
  'ちゃう': 'No no, chau chau — it’s this one.',
  'べらぼうめ': "Beraboume! Don't mess with me.",
  'てやんでい': "Teyandei! I'm a true Edo kid.",
  'おととい来やがれ': 'A deal like that? Ototoi kiyagare!',
  '野暮': 'Asking that is so yabo.',
  '粋': 'Their style is so iki.',
  'すっとこどっこい': 'You suttokodokkoi!',
  '草': 'That reply? Kusa.',
  '乙': 'Nice stream — otsu!',
  'ググる': "Don't know it? Just guguru it.",
  '炎上': 'That tweet totally got enjou’d.',
  'ワロタ': 'Caught me off guard — warota.',
  'ROM専': "I'll just go romsen on this thread.",
  '推し': 'My oshi is precious today.',
  '尊い': 'These two together… toutoi.',
  '神回': "This week's episode was a kamikai.",
  '沼': 'That genre is a total numa.',
  '萌え': 'That gesture is pure moe.',
  'ガチ恋': "I'm in gachikoi with that streamer.",
  'それな': '"Mondays suck." "Sorena."',
  'とりま': "Torima, let's just meet up.",
  'わかりみ': 'That struggle? Big wakarimi.',
  '映え': 'This cafe is so bae.',
  'ぴえん': 'It was sold out… pien.',
  'ガチ': "That's gachi delicious.",
  'マブ': 'She’s my mabu — total bestie.',
  'チョリース': 'Choriisu! See ya tomorrow.',
  'ありよりのあり': 'That place? Ari-yori-no-ari for sure.',
  'ガングロ': 'Ganguro was everywhere back then.',
  'あざとい': 'She’s so azatoi… but it works.',
  '盛れる': 'This app totally moreru’s my selfies.',
  'ええやん': "That's ee-yan, let's do it.",
  'しんどい': 'Ugh, today is so shindoi.',
  'ほな': 'Hona, see you tomorrow.',
  'おもろい': "That story's so omoroi.",
  'かまへん': "You're late? Kamahen, no worries.",
  'せやな': '"It’s hot." "Seya na."',
  'いなせ': "He's so inase — proper old-Tokyo cool.",
  'ちゃきちゃき': "She's a chaki-chaki Tokyoite.",
  '御の字': "If we break even, it's on-no-ji.",
  'こちとら': "Kochitora's been at this for years.",
  'すっからかん': "I'm totally sukkarakan till payday.",
  'べらんめえ': "He talks full beranmee — pure Edo.",
  'バズる': "My post totally bazuru'd overnight.",
  '神': "This is a kami feature, honestly.",
  'リア充': "Look at this ria-juu and their plans.",
  '黒歴史': "That old photo is pure kuro-rekishi.",
  'ステマ': "That glowing review smells like sutema.",
  'ポチる': "I just pochiru'd it without thinking.",
  '推し活': "My whole budget goes to oshi-katsu.",
  '二次元': "I only fall for nijigen characters.",
  '厨二病': "He's having a serious chuunibyou phase.",
  '供給': "We're starving — no kyoukyuu this week.",
  '布教': "Let me fukyou my oshi to you real quick.",
  '同担拒否': "She's strictly doutan-kyohi.",
  'なるはや': "Send it naru-haya, please.",
  'ちな': "China, the show starts at 8.",
  '飯テロ': "Your post is straight-up meshi-tero.",
  'きまず': "That silence was so kimazu.",
  'りょ': "\"Bring snacks.\" \"Ryo.\"",
  'バブみ': "She gives off major babu-mi.",
  'いとをかし': "That sunset is ito-wokashi, truly.",
  'もののあはれ': "This whole scene has real mono-no-aware.",
  'かたじけない': "Katajikenai, truly — you saved me.",
  'うつくし': "That kitten is utsukushi in the old sense.",
  'げに': "Geni — you're absolutely right.",
  'まろ': "Maro shall decide this matter.",
  'めんそーれ': "Mensoore — welcome to the islands!",
  'なんくるないさ': "Relax, nankurunaisa.",
  'はいさい': "Haisai! Good to see you.",
  'ちむどんどん': "I'm so chimudondon for this trip.",
  'でーじ': "It's deeji hot out here.",
  'にふぇーでーびる': "Nifee-deebiru for everything!",
  'チョベリグ': "These nails are so cho-beri-gu!",
  'あげあげ': "That party had me totally age-age.",
  'テンアゲ': "My jam came on — total ten-age!",
  'さげぽよ': "Got my grade back, totally sage-poyo.",
  'きゃわたん': "Look at that puppy, it's so kyawa-tan!",
  'パツキン': "It's summer — thinking of going patsukin.",
  'マンバ': "Back then everyone was full manba.",
  'コギャル': "My mom was a total kogyaru in the 90s.",
  'チャラい': "That guy's a bit too charai for me.",
  'パネェ': "The heat today is straight-up panee.",
  'プリクラ': "Let's go take some purikura after!",
  'つけま': "Heads up, your tsukema is peeling off.",
  'デコる': "I dekoru'd my whole phone case in rhinestones.",
  'イケメン': "My new job is full of ikemen.",
  'ダサい': "That outfit combo is a little dasai, ngl.",
  'ウケる': "Omg that's so ukeru.",
  'ビミョー': "Honestly the food was bimyou.",
  'メンディー': "So much homework, it's mendii.",
  'ありえない': "Bailing last minute is just arienai.",
  'ヤンキー': "My teacher was apparently a real yankii.",
  'ノリ': "I bought it totally on the nori.",
  'イケてる': "That haircut is so iketeru.",
  'あざーす': "You got the bill? Azaasu!",
  'うぇーい': "It's Friday night — weei!",
  'ギャル男': "Shibuya was full of gyaru-o back then.",
  '盛り': "Today I'm going full mori with the hair.",
  'がっつり': "I wanna eat gattsuri today.",
  'ちょりっす': "Chorissu! You good?",
  'ほぼほぼ': "I'm hobo-hobo done with prep.",
  'うざい': "These notifications are so uzai.",
  'きもい': "Ew that bug is so kimoi.",
  'ガン無視': "They left me on read and gan-mushi'd me.",
  'じもてぃー': "I'm seeing my jimotii over the holidays.",
  'あほ': "What are you doing, you total aho.",
  'どないやねん': "No booking?? Donai yanen!",
  'せやで': "Is that correct? Seya-de!",
  'ほんで': "Honde, what happened next?",
  'まいど': "Maido! Good deals again today.",
  'なんぼ': "Hey, kore nanbo? How much?",
  'ぎょうさん': "I made gyousan food, dig in.",
  'ようけ': "There were youke people there.",
  'しゃあない': "It's raining — shaanai, what can you do.",
  'かなん': "This heat is honma kanan.",
  'いちびり': "He's such an ichibiri, always clowning.",
  'どんくさい': "You're being so donkusai today.",
  'けったい': "This has a kettai flavor, huh.",
  'えげつない': "This portion is straight-up egetsunai.",
  'いけず': "Aww, don't be ikezu to me.",
  'なおす': "Can you naosu the dishes for me?",
  'ほかす': "Can I hokasu this already?",
  'さら': "This notebook is still totally sara.",
  'べっぴん': "Your daughter's a real beppin.",
  'ごっつ': "This is gottsu delicious!",
  'しょうもない': "Stop with the shoumonai jokes.",
  'ほんなら': "Honnara, I'll get going.",
  'かいらしい': "What a kairashii little one.",
  'なんでやのん': "Wait, nande-yanon?",
  'おもんない': "Honestly that's omonnai.",
  'なんや': "Nanya, what's with that face?",
  'あんじょう': "Make sure you do it anjou, yeah?",
  'どや': "Doya! Tasty, right?",
  'ちゃうちゃう': "Chau-chau, that's not it!",
  'もうかりまっか': "Hey boss — moukarimakka?",
  'ぼちぼち': "How's it going? Bochi-bochi, you know.",
  'まいど おおきに': "Maido ookini! Come again, yeah?",
  'いてまう': "Keep it up and I'll itemau you.",
  'ちゃちゃっと': "Let's chacha-tto finish this.",
  'めんどい': "Going out is so mendoi today.",
  'わや': "The whole plan went waya.",
  '江戸っ子': "He's a real edokko, born and bred.",
  '宵越しの銭は持たねえ': "Yoigoshi no zeni wa motanee — that's the Edo way.",
  'ちょいと': "Choito, lemme ask you something.",
  'おかみさん': "Okamisan, can I get the bill?",
  '旦那': "Danna, special price just for you.",
  'ごめんなすって': "Gomen-nasutte, mind if I come in?",
  'あいすまねえ': "Ai-sumanee, I'm late, I know.",
  'ありがとよ': "You bailed me out, arigatoyo.",
  '銭': "No zeni, no entry, pal.",
  '一文無し': "By payday I'm always ichimon-nashi.",
  '朝飯前': "Easy — total asameshi-mae.",
  '屁の河童': "That hill is he-no-kappa for me.",
  'おっちょこちょい': "You forgot again, you occhokochoi.",
  'とんちき': "Quit it, you tonchiki!",
  'おたんこなす': "Stop spacing out, you otankonasu!",
  '宵っ張り': "You're a real yoippari, huh.",
  'おてんとさま': "I can't face otentosama after that.",
  '江戸前': "Real edomae sushi hits different.",
  '拙者': "Sessha is but a humble swordsman.",
  'ござる': "Understood — all is well, de gozaru.",
  '大儀である': "You made it all this way — taigi de aru.",
  '苦しゅうない': "Kurushuu nai — step closer.",
  '近う寄れ': "Don't be shy — chikou yore.",
  '成敗': "Villain! Time for seibai!",
  '御免': "Gomen! Coming through.",
  '申す': "Sessha — Sanjuro to mousu.",
  '武士に二言はない': "I keep my word. Bushi ni nigon wa nai.",
  '拙宅': "Please visit settaku sometime.",
  '手前': "Temee! How dare you.",
  'やい': "Yai! Hold up right there.",
  'おうとも': "Am I in? Outomo!",
  'あたぼうよ': "Can we win? Atabou yo!",
  'おひけえなすって': "O-hikee-nasutte — let me introduce myself.",
  'いよっ、待ってました': "Iyo, matte-mashita! Bravo!",
  'ggrks': "Bro, that's a ggrks question.",
  '大草原': "That ending is straight daisougen.",
  'フイタ': "Saw that and totally fuita.",
  'ぐぬぬ': "You're right and I hate it — gununu.",
  '厨': "The comments are full of niwaka-chuu.",
  '信者': "That brand has serious shinja energy.",
  'アンチ': "It's just the anchi making noise.",
  '垢': "I just made a new aka.",
  '裏垢': "I vent on my ura-aka.",
  '鍵垢': "I'm on kagi-aka, so request to follow.",
  '凍結': "My account got touketsu'd for spam.",
  'リプ': "No ripu yet, kinda sad.",
  '拡散': "It says 'kakusan please' at the end.",
  '凸': "I totsu'd the mods about it.",
  'スレ': "That sure already got archived.",
  '名無し': "Some nanashi said it but it's fair.",
  '釣り': "That headline was pure tsuri.",
  'マジレス': "Don't majiresu to an obvious joke.",
  'スルー': "Just suruu the haters, it's best.",
  '既読スルー': "They kidoku-suruu'd me for days.",
  '情弱': "That's a joujaku trap, careful.",
  'テンプレ': "Check the tenpure before you ask.",
  '自演': "Bro, your jien is obvious.",
  'なりすまし': "Careful, that's a narisumashi account.",
  'リムる': "They got annoying so I rimuru'd them.",
  'フォロバ': "Thanks for the foroba!",
  '相互': "Wanna interact with my sougo more.",
  '過疎': "This server is so kaso now.",
  'まとめ': "Saw it on a matome site.",
  'コテハン': "He's a famous kotehan on that board.",
  'ワンチャン': "Wanchan we still make it.",
  '把握': "Ok, haaku — understood.",
  'うp': "Uppu the pic, pretty please.",
  'ネタ': "Chill, it's just a neta.",
  '垢消し': "After the backlash they did an aka-keshi.",
  'ワロス': "That typo is so bad, warosu.",
  '箱推し': "I'm hako-oshi — I love the whole group.",
  '単推し': "I'm strictly tan-oshi, just her.",
  '推し変': "I did a surprise oshi-hen, oops.",
  '同担': "I bonded with a doutan today.",
  '担当': "My tantou is the red-color one.",
  '現場': "I'm going to the genba this weekend.",
  '参戦': "Dome show sansen, locked in!",
  '遠征': "I did an ensei all the way to Osaka.",
  'ペンラ': "I matched my penra to her color.",
  '神対応': "At the event she gave total kami-taiou.",
  '塩対応': "Got a little shio-taiou today, sad.",
  '認知': "I think I got ninchi'd — she knows me!",
  'チェキ': "Got two cheki at the meet.",
  '在宅': "I've been doing zaitaku fandom lately.",
  '卒業': "My oshi announced sotsugyou — I'm devastated.",
  'リアコ': "I'm full riako for him, it's bad.",
  '夢女子': "I'm a total yumejoshi, no shame.",
  '腐女子': "I've been a fujoshi for a decade.",
  '限界オタク': "I'm a full genkai-otaku right now.",
  '語彙力': "So precious… goiryoku gone…",
  '沼落ち': "One episode and I numa-ochi'd hard.",
  'オタ活': "My paycheck vanished into otakatsu.",
  'オタ芸': "The front row's otagei is next-level.",
  '聖地巡礼': "I did a seichi-junrei to the anime spots.",
  '痛バ': "My itaba is done — I carry it proudly.",
  'ぬい': "I bring my nui everywhere I travel.",
  '円盤': "I pre-ordered the enban for the extras.",
  '二次創作': "The niji-sousaku is what got me hooked.",
  '同人': "I'm tabling at a doujin event.",
  '配信': "There's a haishin tonight at 9.",
  'スパチャ': "I dropped a supacha for my oshi.",
  '切り抜き': "I got into them via kirinuki.",
  '推ししか勝たん': "Honestly, oshi shika katan, period.",
  '尊死': "Her smile is straight-up tooto-shi.",
  '担降り': "After all that, I did a tan-ori.",
  '蛙化現象': "We matched and bam — kaeruka-genshou.",
  '親ガチャ': "Honestly I hit the oya-gacha jackpot.",
  'タイパ': "I watch on 2x — it's all about taipa.",
  'コスパ': "This spot has insane kosupa.",
  '陰キャ': "At recess I did full in-kya mode.",
  '陽キャ': "She's a total you-kya, life of the party.",
  'コミュ障': "I can't do calls, I'm komyushou.",
  'ぼっち': "I had a bocchi lunch again today.",
  'チル': "Gonna chiru at home all day.",
  'ととのう': "After the cold plunge I totally totonou'd.",
  'マウント': "She always takes the maunto on me.",
  '無理ゲー': "This deadline is a total murige.",
  '詰んだ': "Forgot my wallet, totally tsunda.",
  'きゅんです': "That move? Kyun-desu, instantly.",
  '知らんけど': "It'll be sunny, shiran kedo.",
  'それはそう': "Should sleep early? Sore wa sou.",
  'ま？': "Class is cancelled? Ma??",
  'つらみ': "Monday mornings are pure tsurami.",
  'うれしみ': "My oshi's streaming — ureshimi!",
  '地雷系': "Your jirai-kei makeup is on point.",
  '量産型': "Going full ryousan-gata today.",
  'ぴえん超えてぱおん': "So good I'm pien koete paon.",
  'きしょい': "That vibe is straight-up kishoi.",
  'かまちょ': "That's such a kamacho post, lol.",
  'フロリダ': "Gonna furorida real quick, brb.",
  'ガチ勢': "That community is all gachizei.",
  '情緒不安定': "My oshi has me totally joucho-fuantei.",
  'やばたん': "I overslept — yabatan!",
  'それな案件': "Mondays being rough is a sorena-anken.",
  '推し疲れ': "I overspent and hit oshi-zukare.",
  '蛙化': "One little thing and I kaeruka'd.",
  '限界': "Too cute, I'm at my genkai.",
  'おじ構文': "So many emojis, pure oji-koubun.",
  'あはれ': "This moonlight is so aware, truly.",
  'いみじ': "This view is imiji — beyond words.",
  'ゆかし': "That hidden garden feels so yukashi.",
  'めでたし': "The cherry blossoms are truly medetashi.",
  'らうたし': "That sleeping baby is utterly rautashi.",
  'はかなし': "Life feels so hakanashi sometimes.",
  'つれづれ': "In my tsurezure I just doodle all day.",
  'ものぐるほし': "Writing all day left me monoguruhoshi.",
  'あけぼの': "Spring is all about the akebono.",
  'つとめて': "Winter mornings, the tsutomete chill.",
  'やうやう': "The sky youyou turning light at dawn.",
  'いと': "This is ito beautiful, truly.",
  'いざ': "Iza — let's set off!",
  'あな': "Ana! How wonderful!",
  'さらなり': "On a moonlit night it's saranari lovely.",
  'わろし': "Honestly that take is a bit waroshi.",
  'よろし': "That poem is yoroshi, decent enough.",
  'うし': "Everything feels ushi today.",
  'こひし': "I feel so koishi for home.",
  'ながむ': "I just nagamu the sky when I'm sad.",
  'おはす': "Where does the lord owasu now?",
  'たまふ': "The lord tamau'd his command.",
  'はべり': "I haberi here in the capital, my lord.",
  'みかど': "By the mikado's decree.",
  'きさき': "She served the kisaki at court.",
  'にょうぼう': "The nyoubou gossiped behind the screen.",
  'ふみ': "Send me a fumi soon, won't you.",
  'うた': "He sent her an uta to confess.",
  'すくせ': "Maybe meeting you was sukuse.",
  'もののけ': "They blamed it on a mononoke.",
  'みやび': "The whole ceremony had such miyabi.",
  'いろごのみ': "Genji was the ultimate irogonomi.",
  'けそう': "He's been kesou over her for months.",
  'かいまみ': "He fell for her after one kaimami.",
  'きぬぎぬ': "He wrote her a kinuginu letter at dawn.",
  'あやし': "There's something ayashi about this place.",
  'つきづきし': "That outfit is so tsukizukishi for the scene.",
  'なまめかし': "Her bearing was so namamekashi.",
  'あだなり': "Their promise felt adanari from the start.",
  'うるはし': "Everything was so uruwashi and proper.",
  'すさまじ': "An empty hall at night feels susamaji.",
  'はいたい': "Haitai! You doing okay?",
  'いっぺーまーさん': "This soba is ippee maasan, wow.",
  'まーさん': "Grandma's cooking is so maasan.",
  'くゎっちーさびら': "Everyone's here? Kwacchii sabira!",
  'くゎっちーさびたん': "That was great — kwacchii sabitan!",
  'うさがみそーれー': "Don't be shy, usagamisoore!",
  'かめーかめー': "Grandma launched her kamee-kamee attack.",
  'あきさみよー': "Akisamiyoo! I forgot my wallet!",
  'だからよー': "So hot today. — Dakarayoo!",
  'とー': "Too! Let's get started.",
  'ちむぐくる': "This island is full of chimugukuru.",
  'ちむぐりさ': "Watching that gave me chimugurisa.",
  'てーげー': "Just keep it teegee, no stress.",
  'いちゃりばちょーでー': "Icharibachoodee — you're family now!",
  'かりー': "Karii! Here's to good fortune!",
  'うちなーんちゅ': "Proud to be uchinaanchu.",
  'やまとぅんちゅ': "For a yamatunchu, this is all new.",
  'うちなーぐち': "I want to learn some uchinaaguchi.",
  'うちなー': "The sea in uchinaa is unreal.",
  'がんじゅー': "You staying ganjuu, yeah?",
  'ゆんたく': "We yuntaku'd for hours on the porch.",
  'まじゅん': "Let's go majun, yeah?",
  'わじわじー': "This traffic has me wajiwajii.",
  'あがー': "Agaa! That hurt!",
  'しに': "This is shini good, wow.",
  'まぎー': "That's a magii portion, whoa.",
  'かなさん': "My little one is so kanasan.",
  'ぐすーよー': "Gusuuyoo, hello to you all!",
  'ちゅーうがなびら': "Chuu uganabira! Good to see you.",
  'わん': "Wan will handle it, don't worry.",
  'いゃー': "Hey iyaa, where you headed?",
  'やいびーん': "I'm a student yaibiin.",
  'ぐぶりーさびたん': "Sorry I'm late — guburii sabitan.",
  'うとぅいむち': "Okinawan utuimuchi is next-level.",
  'にーびち': "My cousin's niibichi is this weekend.",
  'ちゅらかーぎー': "She's a real chura-kaagi.",
  'ちゅらさん': "This beach is so churasan.",
  'ちゃーびらさい': "Chaabira sai — anyone home?",
  'ドパガキ': "Sorry, I'm such a dopagaki, I can't sit still.",
  'メロい': "His smile is so meroi, I can't.",
  '好きすぎて滅': "I love this song suki sugite metsu.",
  'ビジュ': "Your biju is amazing today.",
  'キャパい': "Four reports at once? I'm so kyapai.",
  'てぇてぇ': "Those two together are so teetee.",
  'ウマ確': "This burger is uma-kaku, trust.",
  '風呂キャン': "I did a furo-kyan again, oops.",
  'ビジュ爆発': "She's having a biju-bakuhatsu moment.",
  'エッホエッホ': "Ehho-ehho! Gotta tell everyone the news!",
  'ほんmoney': "My oshi replied?! Hon-money!!",
};

// JP → EN labels for temperature tags (English-first chrome).
const ERA_EN: Record<string, string> = {
  '平成ギャル (2000s)': 'Heisei gal (2000s)',
  '平成ギャル (90s-2000s)': 'Heisei gal (90s–2000s)',
  'コギャル (90s)': 'Kogal (90s)',
  '平成後期〜令和': 'Late Heisei–Reiwa',
  '令和': 'Reiwa (now)',
  '令和 JK': 'Reiwa schoolgirls',
  '現役': 'Still current',
  '江戸': 'Edo era',
  '江戸発・現役': 'Edo-origin, still used',
  '令和ネット': 'Reiwa internet',
  'ネット老人(2000s-)': 'Old-net (2000s–)',
  'ネット(掲示板)': 'Forum-era net',
  '令和オタク': 'Reiwa otaku',
  '平成オタク(2000s)': 'Heisei otaku (2000s)',
  '令和(2020ピーク)': 'Reiwa (2020 peak)',
  '令和(平成後期〜)': 'Reiwa (late-Heisei on)',
  '平安': 'Heian era',
  '沖縄(現役)': 'Okinawa, current',
  '平成ギャル': "Heisei gal era",
  '関西': "Kansai",
  'ネット': "Internet",
  'オタク文化': "Otaku culture",
  '沖縄': "Okinawa",
};
const WHO_EN: Record<string, string> = {
  'ギャル / JK': 'Gals / schoolgirls',
  'コギャル': 'Kogals',
  '若者': 'Young people',
  '若者全般': 'Young people',
  'JK / 若者': 'Schoolgirls / youth',
  '関西の人 / 商売人': 'Kansai folks / shopkeepers',
  '関西の人': 'Kansai folks',
  '関西発・全国区': 'Kansai-born, nationwide',
  '江戸っ子 / 時代劇': 'Edo locals / samurai dramas',
  '江戸っ子 / 職人': 'Edo locals / artisans',
  '江戸っ子': 'Edo locals',
  '現代でも通じる': 'Still understood today',
  '江戸っ子 / 落語': 'Edo locals / rakugo',
  'ネット民全般': 'Netizens',
  'ネット民 / 配信': 'Netizens / streamers',
  'ほぼ全員': 'Almost everyone',
  'メディア含む全般': 'Everyone, incl. media',
  '古参ネット民': 'Veteran netizens',
  '掲示板/コミュ勢': 'Forum / community users',
  'ファン全般': 'Fans',
  'オタク / 推し活': 'Otaku / oshi fans',
  '視聴者全般': 'Viewers',
  'オタク / 趣味勢': 'Otaku / hobbyists',
  '古参オタク': 'Veteran otaku',
  '推し活 / 配信勢': 'Oshi fans / streamer fans',
  '若者中心・全般': 'Mainly youth',
  '若者 / SNS': 'Youth / social media',
  '若者 / JK': 'Youth / schoolgirls',
  '平安貴族': 'Heian court nobles',
  '古典・時代劇': 'Classical / samurai dramas',
  '沖縄の人': 'Okinawans',
  'ギャル': "Gals",
  'JK': "High-school girls",
  '武士': "Samurai",
  'ネット民': "Netizens",
  'ドルオタ': "Idol fans",
  'オタク': "Otaku fans",
  'うちなーんちゅ': "Okinawans",
};

export function loadPhrases(): Phrase[] {
  const all = [...gyaru, ...kansai, ...edo, ...net, ...otaku, ...reiwa, ...heian, ...okinawa] as Phrase[];
  return all.map(validatePhrase).map((p) => ({
    ...p,
    exampleMix: MIX[p.term] ?? p.exampleMix,
    tag: {
      ...p.tag,
      eraEn: ERA_EN[p.tag.era] ?? p.tag.eraEn,
      whoUsesEn: WHO_EN[p.tag.whoUses] ?? p.tag.whoUsesEn,
    },
  }));
}

export function loadPhrasesByCategory(categoryId: string): Phrase[] {
  return loadPhrases().filter((p) => p.categoryId === categoryId);
}
